import { Navbar } from "@/components/Navbar/Navbar";
import { Montserrat } from "next/font/google";
import { Footer } from "@/components/Footer/Footer";
import MobileMenu from "@/components/Navbar/MobileMenu";
import DesktopMenu from "@/components/Navbar/DesktopMenu";

import "./globals.scss";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params: { lang } }) {

  return (
    <html lang={lang}>
      <body className={`${montserrat.variable} font-sans`}>
        <Navbar>
          <MobileMenu pageLanguage={lang}/>
          <DesktopMenu pageLanguage={lang}/>
        </Navbar>
        <main className="main-content">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
