import { Navbar } from "@/components/Navbar/Navbar";
import "./globals.scss";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <div className="container bg-black">
          <Navbar />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
